#!/bin/bash
set -e

cp -p examples/*.{c,cpp,hpp} "$AUTOPKGTEST_TMP"/
cd "$AUTOPKGTEST_TMP"

for x in autohbw_candidates.c filter_example.c hello_hbw_example.c hello_memkind_example.c
  do
    echo "=== $x ==="
    gcc -Wall "$x" -lmemkind
  done

for x in memkind_allocated_example.cpp
  do
    echo "=== $x ==="
    g++ -Wall "$x" -lmemkind
  done
